### ISSUE TITLE
RefBaseSystemUnitPath to the SUC UaMethodNodeClass is incorrectly escaped

### ISSUE THREAD

**Issue by HochMEE** [OPCF-Members/Opc2Aml#12]
The RefBaseSystemUnitPath to the SUC UaMethodNodeClass is the following:
RefBaseSystemUnitPath="[SUC_OpcAmlMetaModel]/[UaMethodNodeClass]"

It is unnecessary to escape the above both and it should be the following:
RefBaseSystemUnitPath="SUC_OpcAmlMetaModel/UaMethodNodeClass"

![Escaping](https://user-images.githubusercontent.com/117661023/200352984-e1b2789c-3b99-47e8-88a9-8633fc53801b.PNG)

**Comment by ekolb** [comment]
This is not to fix. It does not break the CAEX specification. Team aggrees toclose it.

**Comment by Archie-Miller** [comment]
Closing issue as to group discussion on January 13 2023
