### ISSUE TITLE
Unusual BuiltInType values should be supported in conversion

### ISSUE THREAD

**Issue by Archie-Miller** [OPCF-Members/Opc2Aml#18]
BuiltInTypes like

- LocalizedText
- Guid
- ByteString
- XmlElement
- NodeId
- ExpandedNodeId
- StatusCode
- QualifiedName

**Comment by Archie-Miller** [comment]
Removing LocalizedText, as an issue has been specifically created.

[Issue 21](https://github.com/OPCF-Members/Opc2Aml/issues/21)

**Comment by ekolb** [comment]
agreed to close
