### ISSUE TITLE
Description should be included in conversion, if one is provided

### ISSUE THREAD

**Issue by Archie-Miller** [OPCF-Members/Opc2Aml#19]
I wonder whether UA DisplayNames are represented in AML.

In part 83 OE we write:

![image001](https://github.com/OPCF-Members/Opc2Aml/assets/62433534/91296f3e-d486-4c8a-b39a-9db70e8237c5)

So when there is no difference the DisplayName can be omitted.

But what happens, if there is a difference ?

In the PADIM Nodeset many nodes have different DisplayNames, but I could not find a Displayname attribute in the generated AML.

I can confirm that the DisplayName attribute is not being set when it is different than the Browse Name, although it looks like a simple addition

**Comment by Archie-Miller** [comment]
This should be DisplayName, not description, as per email conversation DisplayNames in AML February 6,7 2023

**Comment by Archie-Miller** [comment]
This was resolved on March 8 2023 alongside Issue 21.

**Comment by Archie-Miller** [comment]
Description is not being propogated, still working on this issue.

**Comment by ekolb** [comment]
Agreed to close in OE meeting
