### ISSUE TITLE
Generate static, unique IDs for InternalElements

### ISSUE THREAD

**Issue by JimLuth** [OPCF-Members/Opc2Aml#2]
AML InternalElements require an ID. Currently the AMLEngine automatically creates a GUID ID for all InternalelElements when they are created so each time the NodeSet to AML tools is run, the objects all get new IDs. This violates the AutomationML standard as the IDs are expected to stay the same unless the object is materially altered.

The suggested implementation is to use the UA XML representation of the Portable NodeId for the AML ID. The string ID would be of the form:

ns=http://opcfoundation.org/UA/;i=492

(Cloned from Mantis #[0008110](https://mantis.opcfoundation.org/view.php?id=8110))

**Comment by ekolb** [comment]
Also SystemUnitClasses and ExternalInterfaces have an ID attribute. These IDs should be covered in the issue as well.

**Comment by ekolb** [comment]
Modification of the proposal from Jim:
- convert the proposed string ID with a hash function to a GUID
This fits better to the way AML tools  are creating IDs
Example:
- String ID: ns=http://opcfoundation.org/UA/;i=492
-  Applying has function md5 creates 128bit hash:
echo -n "ns=http://opcfoundation.org/UA/;i=492" | md5sum
--> dceb215bc718d7c3d345ed2b8b3ab10c
- the hash can be written as 16byte guid:
dceb215b-c718-d7c3-d345-ed2b8b3ab10c

**Comment by Archie-Miller** [comment]
Resolved from group discussion Offline Engineering Group
