### ISSUE TITLE
Many Internal Elements marked as IsAbstract incorrectly

### ISSUE THREAD

**Issue by Archie-Miller** [OPCF-Members/Opc2Aml#41]
For Example

InputArguments [nsu%3Dhttp%3A%2F%2Fopcfoundation.org%2FUA%2F%3Bi%3D32555] Marked Abstract when it should not be
OutputArguments [nsu%3Dhttp%3A%2F%2Fopcfoundation.org%2FUA%2F%3Bi%3D32556] Marked Abstract when it should not be
OpenCount [nsu%3Dhttp%3A%2F%2Fopcfoundation.org%2FUA%2F%3Bi%3D32550] Marked Abstract when it should not be
UserWritable [nsu%3Dhttp%3A%2F%2Fopcfoundation.org%2FUA%2F%3Bi%3D32549] Marked Abstract when it should not be
Writable [nsu%3Dhttp%3A%2F%2Fopcfoundation.org%2FUA%2F%3Bi%3D32548] Marked Abstract when it should not be
Size [nsu%3Dhttp%3A%2F%2Fopcfoundation.org%2FUA%2F%3Bi%3D32547] Marked Abstract when it should not be

**Comment by ekolb** [comment]
Agreed to close in OE meeting
