### ISSUE TITLE
Values of arrays are not converted like expected.

### ISSUE THREAD

**Issue by HochMEE** [OPCF-Members/Opc2Aml#45]
Please see the attached document and nodeset-file.
[ArrayValues.pdf](https://github.com/OPCF-Members/Opc2Aml/files/12539952/ArrayValues.pdf)
[stringarray.zip](https://github.com/OPCF-Members/Opc2Aml/files/12539956/stringarray.zip)

**Comment by ekolb** [comment]
agreed to close
