### ISSUE TITLE
Unused NodeId TypeIdentifiers can be deled

### ISSUE THREAD

**Issue by HochMEE** [OPCF-Members/Opc2Aml#52]
The ExplicitNodeId consists of the four TypeIdentifiers NumericId, StringId, GuidId and OpqueId. If it is used only one TypeIdentifer shall have a value and the others can be deleted.
![Unused NodeId TypeIdentifiers can be deled](https://github.com/OPCF-Members/Opc2Aml/assets/117661023/d9ae0a79-6839-44eb-9f03-4f5b8b74dbc0)

**Comment by Archie-Miller** [comment]
Issue has been resolved, Demoed, and validated as of January 26 2024
