### ISSUE TITLE
If the RootNodeId is used including “NamespaceUri” attribute, the UaNodeNamespaceUri can be deleted.

### ISSUE THREAD

**Issue by HochMEE** [OPCF-Members/Opc2Aml#53]
If the RootNodeId is used including the “NamespaceUri” attribute, the UaNodeNamespaceUri can be deleted. Otherwise the information is dublicated.
![NamespaceUri](https://github.com/OPCF-Members/Opc2Aml/assets/117661023/cd1641a9-7367-4849-8c25-a8910dc83fd9)

**Comment by Archie-Miller** [comment]
Need to remove UaNodeNamespaceUri - Add to metamodel

**Comment by Archie-Miller** [comment]
Issue has been resolved, Demoed, and validated as of January 26 2024
